---
version: '3'
services:
  miso:
    image: ghcr.io/mikecao/miso:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://miso:miso@db:5432/miso
      DATABASE_TYPE: postgresql
      HASH_SALT: replace-me-with-a-random-string
    depends_on:
      - db
    restart: always
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: miso
      POSTGRES_USER: miso
      POSTGRES_PASSWORD: miso
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - miso-db-data:/var/lib/postgresql/data
    restart: always
volumes:
  miso-db-data:
